# Generated by Django 4.2.13 on 2024-06-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
    ]
