# Generated by Django 4.2.13 on 2024-06-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_order_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
